image: androidsdk/android-30
pipelines:
  branches:
    test:
      - step:
          size: 2x
          name: Android Release Application
          caches:
            - gradle
          script:
            - chmod +x gradlew
            - echo "$KEY_STORE_FILE_BASE64" | base64 -d > keystore.jks
            - ./gradlew assembleDevelopRelease
          artifacts:
            - app/build/outputs/**
      - step:
          name: Deploy To Firbase App Distribution
          caches:
            - gradle
          script:
            - chmod +x gradlew
            - echo "$FIREBASE_SERVICE_ACCOUNT_KEY" | base64 -d > service-account-key.json
            - ./gradlew --stop
            - ./gradlew appDistributionUploadDevelopRelease
          artifacts:
            - app/build/outputs/**
